#!/usr/bin/env perl

use strict;
use warnings;

if($#ARGV != 1) {
    print "USAGE: tools/mkiso <objdir> <isodir>\n";
    exit 1;
}

my $pwd = `pwd`; chomp($pwd);
my $objdir = $pwd . "/" . $ARGV[0];
my $isodir = $pwd . "/" . $ARGV[1];

if(system(qq(xorriso -help >/dev/null))) {
    print "Must have xorriso installed!\n";
    print "Trying to apt-get...\n";
    if(system(qq(sudo apt-get install xorriso))) {
        print "Failed. Exiting\n";
        exit 1;
    }
}

system(qq(cp $objdir/kern/kernel $isodir/boot/jos-grub));

my $cmd = qq(xorriso -as mkisofs -R -b boot/grub/stage2_eltorito )
        . qq(-no-emul-boot -boot-load-size 4 -input-charset ASCII  )
        . qq(-boot-info-table -o $objdir/bootable.iso $isodir);

printf("$cmd\n");

if(system($cmd)) {
    print "failed to generate iso image!\n";
    exit 1;
}

exit 0;
