#!/usr/bin/env perl


for my $file (split "\n", `find fs obj/fs obj/user -type f`) {
    if(($file =~ /Make/) || ($file =~ /fs/)) {
        next;
    }

    if($file =~ /\/[^\/\.]+$/) {
        print("cp $file root/\n");
        system("cp $file root/");
    }
}
