#!/usr/bin/env perl

if(not (-s "obj/bootable.iso")) {
    die("Need an iso!");
}

if(not (-s "obj/fs/fs.img")) {
    die("Need a filesystem!");
}

my $pwd = `pwd`; chomp($pwd);
my $iso = "$pwd/obj/bootable.iso";
my $fs = "$pwd/obj/fs/fs.img";
my $conf = "$pwd/obj/xenjos.cfg";
my $exitcode = 0;

my $grub = "";

# Prefer pv-grub to pygrub

for my $file (split "\n", `find /usr/lib`) {
    chomp($file);
    if(($file =~ /pv-grub/) and ($file =~ /\.gz/)) {
        $grub = qq(kernel = '$file');
    }
}

if(length($grub) == 0) {
    for my $file (split "\n", `find /usr/lib`) {
        chomp($file);
        if (($file =~ /pygrub/) and ($file =~ /\/[^\/\.]+$/)) {
            $grub = qq(bootloader = '$file');
        }
    }
}

if(length($grub) == 0) {
    print("Couldn't find pvgrub or pygrub in /usr/lib!\n");
    $exitcode = 1;
}

open(my $fh, '>', $conf)
    or die "Could not new config file '$conf'!";
print $fh (<<EOF

name                  = "broke-ass-hoe"
firmware_override     = "/usr/lib/xen/xen-4.4/boot/hvmloader"
builder               = 'hvm'
memory                = 256
vcpus                 = 1
vif                   = ['model=e1000']
disk                  = ['file:$iso,hda:cdrom,r'];
acpi                  = 0
device_model_override = '/usr/bin/qemu-system-i386'
sdl                   = 0
serial                = 'pty'
vnc                   = 0

EOF
);

close $fh;

exit $exitcode;
