#!/usr/bin/env perl

use warnings;
use strict;

open(my $fh, '>', "isofiles/boot/grub/menu.lst")
    or die "Couldn't fix menu.lst for qemu!";
print $fh (<<EOF
default 0
timeout 0

title JOS
root (hd0)
kernel /boot/jos-grub
EOF
);

close $fh;


